dist: xenial
language: csharp
dotnet: 2.1.502
mono: none

install:
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
 - curl https://origin-download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
 - sudo apt install apt-transport-https ca-certificates -y
 - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
 - sudo apt update
 - sudo apt install mono-devel

script:
 - mono ./.paket/paket.exe install
 - dotnet restore
 - dotnet build
 - dotnet test
