dist: xenial
language: csharp
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - PATH="$PATH:$HOME/.dotnet/tools"
    - DOTNET_ROOT="/snap/dotnet-sdk/current/sdk/3.0.100-preview7-012821"

addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta

install:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet tool install -g paket

script:
 - paket install
 - dotnet restore
 - dotnet build
 - dotnet test
